-- CreateTable
CREATE TABLE "OzelSiparis" (
    "id" TEXT NOT NULL,
    "musteriAdi" TEXT NOT NULL,
    "musteriTelefon" TEXT,
    "musteriId" TEXT,
    "satisSiparisId" TEXT,
    "subeId" TEXT,
    "subeAdi" TEXT,
    "sirketId" INTEGER,
    "tip" TEXT NOT NULL,
    "urunAdi" TEXT NOT NULL,
    "urunKodu" TEXT,
    "miktar" INTEGER NOT NULL DEFAULT 1,
    "sagSph" DOUBLE PRECISION,
    "sagCyl" DOUBLE PRECISION,
    "sagAks" DOUBLE PRECISION,
    "sagAdd" DOUBLE PRECISION,
    "sagPd" DOUBLE PRECISION,
    "solSph" DOUBLE PRECISION,
    "solCyl" DOUBLE PRECISION,
    "solAks" DOUBLE PRECISION,
    "solAdd" DOUBLE PRECISION,
    "solPd" DOUBLE PRECISION,
    "camTipi" TEXT,
    "camIndeksi" TEXT,
    "kaplama" TEXT,
    "cerceveBilgisi" TEXT,
    "tedarikciId" INTEGER,
    "tedarikciAdi" TEXT,
    "tedarikciSiparisNo" TEXT,
    "tahminiMaliyet" DOUBLE PRECISION,
    "satisFiyati" DOUBLE PRECISION,
    "durum" TEXT NOT NULL DEFAULT 'BEKLIYOR',
    "notlar" TEXT,
    "tahminiGelisTarihi" TIMESTAMP(3),
    "gercekGelisTarihi" TIMESTAMP(3),
    "teslimTarihi" TIMESTAMP(3),
    "olusturanKullanici" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "OzelSiparis_pkey" PRIMARY KEY ("id")
);
