-- AlterTable
ALTER TABLE "Customer" ADD COLUMN     "eRx_date" TEXT,
ADD COLUMN     "eRx_diagnosis" TEXT,
ADD COLUMN     "eRx_doctor" TEXT,
ADD COLUMN     "eRx_hospital" TEXT,
ADD COLUMN     "eRx_no" TEXT,
ADD COLUMN     "far_l_aks" TEXT,
ADD COLUMN     "far_l_cyl" TEXT,
ADD COLUMN     "far_l_diagnosis" TEXT,
ADD COLUMN     "far_l_pd" TEXT,
ADD COLUMN     "far_l_sph" TEXT,
ADD COLUMN     "far_r_aks" TEXT,
ADD COLUMN     "far_r_cyl" TEXT,
ADD COLUMN     "far_r_diagnosis" TEXT,
ADD COLUMN     "far_r_pd" TEXT,
ADD COLUMN     "far_r_sph" TEXT,
ADD COLUMN     "hasPresciption" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "lens_l_add" TEXT,
ADD COLUMN     "lens_l_aks" TEXT,
ADD COLUMN     "lens_l_bc" TEXT,
ADD COLUMN     "lens_l_cyl" TEXT,
ADD COLUMN     "lens_l_sph" TEXT,
ADD COLUMN     "lens_r_add" TEXT,
ADD COLUMN     "lens_r_aks" TEXT,
ADD COLUMN     "lens_r_bc" TEXT,
ADD COLUMN     "lens_r_cyl" TEXT,
ADD COLUMN     "lens_r_sph" TEXT,
ADD COLUMN     "near_l_aks" TEXT,
ADD COLUMN     "near_l_cyl" TEXT,
ADD COLUMN     "near_l_diagnosis" TEXT,
ADD COLUMN     "near_l_pd" TEXT,
ADD COLUMN     "near_l_sph" TEXT,
ADD COLUMN     "near_r_aks" TEXT,
ADD COLUMN     "near_r_cyl" TEXT,
ADD COLUMN     "near_r_diagnosis" TEXT,
ADD COLUMN     "near_r_pd" TEXT,
ADD COLUMN     "near_r_sph" TEXT;
