-- CreateTable
CREATE TABLE "CustomerPrescription" (
    "id" TEXT NOT NULL,
    "customerId" TEXT NOT NULL,
    "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "source" TEXT NOT NULL DEFAULT 'MANUAL',
    "far_r_pd" TEXT,
    "far_r_sph" TEXT,
    "far_r_cyl" TEXT,
    "far_r_aks" TEXT,
    "far_r_note" TEXT,
    "far_l_pd" TEXT,
    "far_l_sph" TEXT,
    "far_l_cyl" TEXT,
    "far_l_aks" TEXT,
    "far_l_note" TEXT,
    "near_r_pd" TEXT,
    "near_r_sph" TEXT,
    "near_r_cyl" TEXT,
    "near_r_aks" TEXT,
    "near_r_note" TEXT,
    "near_l_pd" TEXT,
    "near_l_sph" TEXT,
    "near_l_cyl" TEXT,
    "near_l_aks" TEXT,
    "near_l_note" TEXT,
    "lens_r_bc" TEXT,
    "lens_r_sph" TEXT,
    "lens_r_cyl" TEXT,
    "lens_r_aks" TEXT,
    "lens_r_add" TEXT,
    "lens_r_note" TEXT,
    "lens_l_bc" TEXT,
    "lens_l_sph" TEXT,
    "lens_l_cyl" TEXT,
    "lens_l_aks" TEXT,
    "lens_l_add" TEXT,
    "lens_l_note" TEXT,
    "eRx_no" TEXT,
    "eRx_date" TEXT,
    "eRx_hospital" TEXT,
    "eRx_doctor" TEXT,
    "eRx_diagnosis" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "CustomerPrescription_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "CustomerPrescription" ADD CONSTRAINT "CustomerPrescription_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
