-- AlterTable
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "odooSaleOrderId" INTEGER;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "odooSynced" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "odooSyncError" TEXT;
